baseurl = "https://4afs.github.io/blog/"
title = "4afS blog"
theme = "coder"
languagecode = "en"
defaultcontentlanguage = "en"
publishDir="docs"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
    author = "Hibiki"
    info = "Likes Haskell and Go."
    description = "4afS's personal website"
    keywords = "blog,developer,personal,programming"
    avatarurl = "img/icon.jpg"

    favicon_32 = "img/favicon-32x32.png"
    favicon_16 = "img/favicon-16x16.png"

    footercontent = "4afS's personal website."

    hidecredits = false
    hidecopyright = false

    rtl = false

    math = true
    custom_css = ["css/custom.css"]

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/4afS/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 2
    url = "https://twitter.com/4afS_/"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "posts/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "about/"
